// Generated code samples
export const CODE_FILES = {
  "main.tf": `# Generated by VRIKSHA.ai 🌿
# Samjhao: यह VPC बनाता है — एक private network
#          जहाँ आपकी services safely run करती हैं

provider "aws" {
  region = var.aws_region
}

resource "aws_vpc" "vriksha_vpc" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Name    = "vriksha-vpc"
    Project = "VRIKSHA.ai"
    Env     = var.environment
  }
}

resource "aws_subnet" "public" {
  count             = 2
  vpc_id            = aws_vpc.vriksha_vpc.id
  cidr_block        = cidrsubnet("10.0.0.0/16", 8, count.index)
  availability_zone = data.aws_availability_zones.available.names[count.index]

  map_public_ip_on_launch = true
}`,

  "dynamodb.tf": `# VRIKSHA.ai — DynamoDB Configuration
# AST Edit: Adding cross-region replica
# Diff applied: +replica block (lines 28-30)

resource "aws_dynamodb_table" "products" {
  name           = "vriksha-products"
  billing_mode   = "PAY_PER_REQUEST"
  hash_key       = "productId"
  range_key      = "createdAt"

  attribute {
    name = "productId"
    type = "S"
  }

  attribute {
    name = "createdAt"
    type = "S"
  }

  # Global Secondary Index for category queries
  global_secondary_index {
    name            = "CategoryIndex"
    hash_key        = "category"
    projection_type = "ALL"
  }

  # 🔬 AST-patched: Cross-region HA replica
  replica {
    region_name = "us-east-2"
  }

  point_in_time_recovery {
    enabled = true
  }

  tags = {
    Name = "vriksha-products-table"
  }
}`,

  "lambda.tf": `# VRIKSHA.ai — Lambda Functions
# Samjhao: Lambda = function जो तभी चलती है
#          जब जरूरत हो। Server 24/7 नहीं चाहिए।

resource "aws_lambda_function" "api_handler" {
  filename         = "dist/handler.zip"
  function_name    = "vriksha-api-handler"
  role             = aws_iam_role.lambda_role.arn
  handler          = "index.handler"
  source_code_hash = filebase64sha256("dist/handler.zip")
  runtime          = "nodejs20.x"
  timeout          = 30
  memory_size      = 512

  environment {
    variables = {
      TABLE_NAME   = aws_dynamodb_table.products.name
      REGION       = var.aws_region
      NODE_OPTIONS = "--enable-source-maps"
    }
  }

  tracing_config {
    mode = "Active"
  }
}`,

  "diff-patch": `--- a/dynamodb.tf
+++ b/dynamodb.tf
@@ -22,6 +22,11 @@ resource "aws_dynamodb_table" "products" {
     projection_type = "ALL"
   }

+  # Cross-region High Availability replica
+  replica {
+    region_name = "us-east-2"
+  }
+
   point_in_time_recovery {
     enabled = true
   }`,
};